package compiler;

public enum NodeType {
	IDENTIFIER,EQUALS,NUMBER,SEMICOLON,WHILE,ELLIPSISOPEN, ELLIPSISCLOSED, 
	BRACKETSOPEN,BRACKETSCLOSE,GREATEREQUALS,MINUS,PLUSVALUE,TOKEN, VARIABELE, IF, IFELSE, ELSE, COMMENTLINE, 
	COMMENTOPEN,COMMENTCLOSE,ECHO,ASSIGN, FOR, STRING;
}
